services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2004:2004"
    environment:
      - SERVER_PORT=2004
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379" # Accessible on your host machine at localhost:6379
    volumes:
      - redis-data:/data # Persists cache data if the container restarts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: