spring.application.name=dronetrics
spring.config.import=optional:file:.env[.properties]
server.port=2004
spring.jackson.mapper.accept-case-insensitive-enums=true
drone.ecase.api.url=${DRONE_ECASE_API_URL:}
drone.ecase.api.bearer-token=${DRONE_ECASE_API_KEY:}
drone.digital.api.url=${DRONE_DIGITAL_API_URL:}
drone.digital.api.bearer-token=${DRONE_DIGITAL_API_KEY:}
drone.api.connection-timeout-seconds=${DRONE_CONNECTION_TIMEOUT_SECONDS:60}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=dronetrics
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=5s
spring.cache.type=redis
logging.level.org.springframework.cache=TRACE
drone.longCacheStartPage=5
#debug=true
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
