spring.application.name=dronetrics
spring.config.import=optional:file:.env[.properties]
server.port=2004
spring.jackson.mapper.accept-case-insensitive-enums=true
drone.ecase.api.url=${DRONE_ECASE_API_URL:}
drone.ecase.api.bearer-token=${DRONE_ECASE_API_KEY:}
drone.digital.api.url=${DRONE_DIGITAL_API_URL:}
drone.digital.api.bearer-token=${DRONE_DIGITAL_API_KEY:}
drone.api.connection-timeout-seconds=${DRONE_CONNECTION_TIMEOUT_SECONDS:60}
