spring.application.name=dronetrics
spring.config.import=file:.env[.properties]
drone.api.url=${DRONE_API_URL:}
drone.api.bearer-token=${DRONE_API_KEY:}
drone.api.connection-timeout-seconds=${DRONE_CONNECTION_TIMEOUT_SECONDS:60}